# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J0OmbEBNrZ732C1tYaMGiEKvv22DmcWY
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime

def fetch_ai_news():
  url = "https://www.itmedia.co.jp/aiplus/"
  headers = {'User-Agent': 'Mozilla/5.0'}
  response = requests.get(url, headers=headers)
  response.encoding = response.apparent_encoding
  soup = BeautifulSoup(response.text, 'html.parser')

  # データの箱を用意
  news_data = []

# 記事タイトルは通常 <h3> <a> などの要素の中にあります
# サイトの構造を分析し、記事リンクっぽいものを抽出します
  articles = soup.find_all('a')

  print("--- AI+ ニュース記事タイトル ---")

  for a in articles:
      text = a.get_text().strip()
    # 条件:10文字以上で「AI」を含むもの
      if len(text) > 10 and "AI" in text:
        #日付とタイトルをセットでリストに追加
          news_data.append({
              "Date":datetime.now().strftime("%Y-%m-%d"),
              "Title":text
          })
          print(f"- {text}")

#CSVとして保存(データがある場合のみ)
  if news_data:
    df = pd.DataFrame(news_data)
    filename = f"ai_news_{datetime.now().strftime('%Y%m%d')}.csv"
    df.to_csv(filename, index=False, encoding='utf-8-sig')
    print(f"\n完了!{filename}に保存しました！")
  else:
    print("\n対象のニュースが見つかりませんでした。")
if __name__=="__main__":
  fetch_ai_news()